apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticvolume
spec:
  storageClassName: elasticlogging
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: elasticshare
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
